import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { useState } from "react";
import { useRouter } from "next/router";

export default function Home() {
  const [count, setCount] = useState(1);

  const router = useRouter();

  const openPage = (e) => {
    e.preventDefault();
    router.push(`/post/${count}`);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Hello nextjs with Amplify</h1>
        <img src="./chart.svg" alt="chart" width={24} height={24} />
        <Link href="/page">Page</Link>
        <p>
          <Link href="/post/1">Posts</Link>
        </p>

        <div>
          page no :
          <input value={count} onChange={(e) => setCount(e.target.value)} />
          <button onClick={openPage}>Go</button>
        </div>
      </main>
    </>
  );
}
